# This file was generated by GoReleaser. DO NOT EDIT.
cask "bumper" do
  version "1.1.0"

  on_macos do
    on_intel do
      sha256 "baa40204fc7a4d0255230c85963cfc3d6dd8450613a43edb0fee1f08704cff3f"
      url "https://github.com/gnana997/bumper/releases/download/v#{version}/bumper_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/gnana997/bumper/"
    end
    on_arm do
      sha256 "8941877b42f1a1c4a6c942b2e21055ea7526e37f03f68e6635aa93f31efc4e17"
      url "https://github.com/gnana997/bumper/releases/download/v#{version}/bumper_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/gnana997/bumper/"
    end
  end

  on_linux do
    on_intel do
      sha256 "fc78e5f5f785731698907212e8d6078900406a77fe0240acbf8125797cf2dd2c"
      url "https://github.com/gnana997/bumper/releases/download/v#{version}/bumper_#{version}_linux_amd64.tar.gz",
        verified: "github.com/gnana997/bumper/"
    end
    on_arm do
      sha256 "f8da77be7baf3757c6863b5c96b85525ce523b30a287ecc93f1be04290cdb8cb"
      url "https://github.com/gnana997/bumper/releases/download/v#{version}/bumper_#{version}_linux_arm64.tar.gz",
        verified: "github.com/gnana997/bumper/"
    end
  end

  name "bumper"
  desc "Catch dangerous Terraform changes before you apply them"
  homepage "https://github.com/gnana997/bumper"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bumper"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bumper"]
    end
  end

  # No zap stanza required

end
