# This file was generated by GoReleaser. DO NOT EDIT.
cask "bumper" do
  version "1.0.0"

  on_macos do
    on_intel do
      sha256 "af5f363d55a1c3c13e80dc69f9e9220fe0b204352ca0307bf372b3b900ad7bd1"
      url "https://github.com/gnana997/bumper/releases/download/v#{version}/bumper_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/gnana997/bumper/"
    end
    on_arm do
      sha256 "7216e55f75f0f2b020047f2883007ae199607429039e06cd6ceff291616013df"
      url "https://github.com/gnana997/bumper/releases/download/v#{version}/bumper_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/gnana997/bumper/"
    end
  end

  on_linux do
    on_intel do
      sha256 "27ec169743f8562bf2b89a00baf020e3d938e83350bc288aa7b10ace7e1b6953"
      url "https://github.com/gnana997/bumper/releases/download/v#{version}/bumper_#{version}_linux_amd64.tar.gz",
        verified: "github.com/gnana997/bumper/"
    end
    on_arm do
      sha256 "2007ea2f233b90750f1444d4052ebce15069fd899815054e058fc1c4acb53634"
      url "https://github.com/gnana997/bumper/releases/download/v#{version}/bumper_#{version}_linux_arm64.tar.gz",
        verified: "github.com/gnana997/bumper/"
    end
  end

  name "bumper"
  desc "Catch dangerous Terraform changes before you apply them"
  homepage "https://github.com/gnana997/bumper"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bumper"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bumper"]
    end
  end

  # No zap stanza required

end
