# This file was generated by GoReleaser. DO NOT EDIT.
cask "bumper" do
  version "1.1.0"

  on_macos do
    on_intel do
      sha256 "f8151af8de6ff449a7a443666dd275e87222ac7fe979eb6a7bee1bf97cea3678"
      url "https://github.com/gnana997/bumper/releases/download/v#{version}/bumper_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/gnana997/bumper/"
    end
    on_arm do
      sha256 "f447a37ea2abfb60c0b031eda3d0647bd5020085f6636ce5006b5c925f67e6e3"
      url "https://github.com/gnana997/bumper/releases/download/v#{version}/bumper_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/gnana997/bumper/"
    end
  end

  on_linux do
    on_intel do
      sha256 "1e5ee0c4bcf3954dd1024ccacbb5957602a9f4b62b213d0ef3c55d8feb69921b"
      url "https://github.com/gnana997/bumper/releases/download/v#{version}/bumper_#{version}_linux_amd64.tar.gz",
        verified: "github.com/gnana997/bumper/"
    end
    on_arm do
      sha256 "0f3e16892818195d56b15b6b7567b95ae92d4731ce8ef48fb4b957a0b37918f2"
      url "https://github.com/gnana997/bumper/releases/download/v#{version}/bumper_#{version}_linux_arm64.tar.gz",
        verified: "github.com/gnana997/bumper/"
    end
  end

  name "bumper"
  desc "Catch dangerous Terraform changes before you apply them"
  homepage "https://github.com/gnana997/bumper"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bumper"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bumper"]
    end
  end

  # No zap stanza required

end
