# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Uispec < Formula
  desc "Give AI agents deep knowledge of your component library"
  homepage "https://github.com/gnana997/uispec"
  version "1.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gnana997/uispec/releases/download/v1.2.0/uispec_1.2.0_Darwin_x86_64.tar.gz"
      sha256 "4293b0f0ec299e748a6d614abcee4ef7c44cecc33639f967b0fb20646a741bda"

      def install
        bin.install "uispec"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gnana997/uispec/releases/download/v1.2.0/uispec_1.2.0_Darwin_arm64.tar.gz"
      sha256 "023a6fec6f38cdb621223e47fb06bcbb4e0c7f38aa42ca167b10cf311796e848"

      def install
        bin.install "uispec"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/gnana997/uispec/releases/download/v1.2.0/uispec_1.2.0_Linux_x86_64.tar.gz"
      sha256 "22bae3ab3315a8e42dae02d8e28b59eccc13b5efea1d2d6d724a83b603d09f44"
      def install
        bin.install "uispec"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/gnana997/uispec/releases/download/v1.2.0/uispec_1.2.0_Linux_arm64.tar.gz"
      sha256 "5aeab0fd794ad453f9409657db847d18d9022d9a6ff5cfc3636b2564dc36fe5f"
      def install
        bin.install "uispec"
      end
    end
  end

  test do
    system "#{bin}/uispec", "version"
  end
end
